# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

# Uncomment this line if you're using Swift
use_frameworks!

workspace ‘SwiftLoginScreen’
xcodeproj 'SwiftLoginScreen’

target 'SwiftLoginScreen' do

pod 'SwiftyJSON', '~> 4.2.0'
pod 'RealmSwift', '~> 3.2'
#pod 'Kanna', '~> 2.1.0'
#pod 'Starscream', '~> 2.0'
#pod 'Franz', '~> 0.1'
end

target 'SwiftLoginScreenTests' do

end

