# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

# Uncomment this line if you're using Swift
use_frameworks!

workspace ‘SwiftLoginScreen’
xcodeproj 'SwiftLoginScreen’

target 'SwiftLoginScreen' do

pod 'SwiftyJSON'
pod 'Realm'
#pod 'Braintree'
#pod 'BraintreeDropIn'
#pod 'Braintree/PayPal'
#pod 'Braintree/Apple-Pay'
#pod 'Kanna', '~> 2.1.0'
#pod 'Starscream', '~> 2.0'
#pod 'Franz', '~> 0.1'
end

target 'SwiftLoginScreenTests' do

end

