//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 02:14:15 PM IST 
//


package com.jeet.api;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Cacheable;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

import org.apache.lucene.analysis.core.LowerCaseFilterFactory;
import org.apache.lucene.analysis.core.StopFilterFactory;
import org.apache.lucene.analysis.snowball.SnowballPorterFilterFactory;
import org.apache.lucene.analysis.standard.StandardTokenizerFactory;
import org.apache.lucene.analysis.standard.StandardFilterFactory;

import org.apache.lucene.analysis.ngram.NGramFilterFactory;
import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.AnalyzerDef;
import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.FullTextFilterDef;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.IndexedEmbedded;
import org.hibernate.search.annotations.Parameter;
import org.hibernate.search.annotations.TokenFilterDef;
import org.hibernate.search.annotations.TokenizerDef;

import com.jeet.db.MovieFullTextSearchFactory;

@Entity
@Indexed
@Cacheable
@AnalyzerDef(name = "customanalyzer",
tokenizer = @TokenizerDef(factory = StandardTokenizerFactory.class),
filters = {
  @TokenFilterDef(factory = StandardFilterFactory.class),
  @TokenFilterDef(factory = LowerCaseFilterFactory.class),
  @TokenFilterDef(factory = SnowballPorterFilterFactory.class, params = {
    @Parameter(name = "language", value = "English")
  }),
  @TokenFilterDef(factory = StopFilterFactory.class),
  @TokenFilterDef(factory = NGramFilterFactory.class,
  params = {
          @Parameter(name = "minGramSize", value = "3"),
          @Parameter(name = "maxGramSize", value = "3")})

})
@FullTextFilterDef(name = "category", impl = MovieFullTextSearchFactory.class)
public class Movie implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 829065582280504436L;
	
	//TODO: add categories!
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Id
    protected int movieId;
	@Field()
	@Analyzer(definition = "customanalyzer")
    protected String name;
	@Field()
	@Analyzer(definition = "customanalyzer")
    protected String detail;
    protected String thumbnail_picture;
    protected String large_picture;
    protected String iMDB_url;
	@Field(analyze = Analyze.NO)
    protected String category;
	/**
	 * List of screen of one movie, one movie to many screening(s)
	 */
    @OneToMany(mappedBy = "movie", fetch=FetchType.LAZY)
    protected List<Screen> screens;

    public Movie () {  	
    }
    
    public Movie(int movieId, String name, String detail, String thumbnail_picture, String large_picture, String iMDB_url) {
    	this.movieId = movieId;
    	this.name = name;
    	this.thumbnail_picture = thumbnail_picture;
    	this.large_picture = large_picture;
    	this.iMDB_url = iMDB_url;
    }
    
    /**
     * Gets the value of the movieId property.
     * 
     */
    public int getMovieId() {
        return movieId;
    }

    /**
     * Sets the value of the movieId property.
     * 
     */
    public void setMovieId(int value) {
        this.movieId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the detail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetail() {
        return detail;
    }

    /**
     * Sets the value of the detail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetail(String value) {
        this.detail = value;
    }

	/**
	 * @return the thumbnail_picture
	 */
	public String getThumbnail_picture() {
		return thumbnail_picture;
	}

	/**
	 * @param thumbnail_picture the thumbnail_picture to set
	 */
	public void setThumbnail_picture(String thumbnail_picture) {
		this.thumbnail_picture = thumbnail_picture;
	}

	/**
	 * @return the iMDB_url
	 */
	public String getiMDB_url() {
		return iMDB_url;
	}

	/**
	 * @param iMDB_url the iMDB_url to set
	 */
	public void setiMDB_url(String iMDB_url) {
		this.iMDB_url = iMDB_url;
	}

	/**
	 * @return the large_picture
	 */
	public String getLarge_picture() {
		return large_picture;
	}

	/**
	 * @param large_picture the large_picture to set
	 */
	public void setLarge_picture(String large_picture) {
		this.large_picture = large_picture;
	}

	/**
	 * @return the category
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * @param category the category to set
	 */
	public void setCategory(String category) {
		this.category = category;
	}
    
    
    /*
    public static void main( String[] args )
    {
        AnnotationConfiguration config = new AnnotationConfiguration();
        config.addAnnotatedClass(Movie.class );
        config.configure();
        new SchemaExport(config).create(true, true);
    }*/
}


