//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 02:14:15 PM IST 
//


package com.jeet.api;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class Logins {
	@Id
	@GeneratedValue(strategy= GenerationType.AUTO)
    protected int id;
    protected String user;
    protected String uuid;
    protected String email;
    protected String profilePicture;


    public int getId() {
        return id;
    }

    public void setId(int value) {
        this.id = value;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String value) {
        this.user = value;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String value) {
        this.uuid = value;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String value) {
        this.email = value;
    }

    public String getProfilePicture() {
        return profilePicture;
    }

    public void setProfilePicture(String value) {
        this.profilePicture = value;
    }
}


